name: Release Drafter

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Draft your next Release notes as Pull Requests are merged into the default branch
      - uses: release-drafter/release-drafter@563bf132657a13ded0b01fcb723c5a58cdd824e2 # v7.2.1
        with:
          config-name: github:shenxianpeng/.github:/.github/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
