name: "Python Code Format"

on:
  push:
    paths:
      - "**.py"
      - .pylintrc
  pull_request:
    types: opened
    paths:
      - "**.py"
      - .pylintrc
  workflow_dispatch:

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install and run pylint
        run: |
          python3 -m pip install --upgrade pylint
      - name: run pylint
        continue-on-error: true
        run: |
          pylint tests/ atlassian/ setup.py release.py
      - name: Install and run black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
          version: "21.5b1"